name = "trolley-scout-organization-email"
main = "workers/organizationEmail.ts"
compatibility_date = "2026-07-01"
workers_dev = false
preview_urls = false

[[send_email]]
name = "EMAIL"
allowed_sender_addresses = [ "access@trolleyscout.co.za", "noreply@trolleyscout.co.za" ]
