// Online storefronts whose deals the scout can read directly.
//
// These shops run a standard commerce platform (Shopify, WooCommerce, Magento,
// VTEX), so the existing platform detector reads their live on-sale feed
// without a per-shop parser. They are listed here rather than in the country
// retailer directory because most have no branch a shopper can walk into: the
// deal is the product, and the directory stays a curated list of chains.
//
// Every entry below was probed against its own platform endpoint in July 2026
// and answered with a live catalogue. A shop with no discount running today is
// still listed — its feed works, so its next markdown is picked up
// automatically.

export interface OnlineStoreSource {
  category: string
  name: string
  url: string
}

const store = (category: string, name: string, url: string): OnlineStoreSource => ({
  category,
  name,
  url,
})

export const ONLINE_STORE_SOURCES: Readonly<Record<string, readonly OnlineStoreSource[]>> = {
  ZA: [
    // Tech, computers and phones
    store('Tech', 'Smartphone Shop', 'https://smartphoneshop.co.za/'),
    store('Tech', 'Revibe', 'https://revibe.co.za/'),
    store('Tech', 'Souk SA', 'https://souksa.co.za/'),
    store('Tech', 'CCTV Direct', 'https://cctv-direct.co.za/'),
    store('Tech', 'Technomobi', 'https://www.technomobi.co.za/'),
    store('Tech', 'JK Phones', 'https://jkphones.co.za/'),
    store('Tech', 'Go Gadgets', 'https://gogadgets.co.za/'),
    store('Tech', 'Super Communications', 'https://www.supercomm.co.za/'),
    store('Tech', 'WeFix', 'https://wefix.co.za/'),
    store('Tech', 'Shop and Ship', 'https://www.shopandship.co.za/'),
    store('Tech', 'TechMarkIt', 'https://techmarkit.co.za/'),
    store('Tech', 'E-piphany', 'https://www.e-piphany.co.za/'),
    store('Tech', 'Cellucity', 'https://cellucity.co.za/'),
    store('Tech', 'Chaos Computers', 'https://chaoscomputers.co.za/'),
    store('Tech', 'TechExchange', 'https://www.techexchange.co.za/'),
    store('Tech', 'PC Shopper', 'https://www.pcshopper.co.za/'),
    store('Tech', 'Device Shop', 'https://deviceshop.co.za/'),
    store('Tech', 'Audio Exchange', 'https://audioexchange.co.za/'),
    store('Tech', 'Security Wholesalers', 'https://securitywholesale.co.za/'),
    store('Tech', 'Audioholics SA', 'https://audioholics.co.za/'),
    store('Tech', 'Just Ink', 'https://justink.co.za/'),
    store('Tech', 'The Cartridge Guy', 'https://thecartridgeguy.co.za/'),
    store('Tech', 'Dell Online South Africa', 'https://www.dellonline.co.za/'),
    store('Tech', 'HP Shop South Africa', 'https://www.hpshop.co.za/'),
    store('Tech', 'ZEEK Online', 'https://www.zeekonline.co.za/'),
    store('Tech', 'ITAD Africa Store', 'https://itadstore.co.za/'),
    store('Tech', 'Only Laptops', 'https://onlylaptops.co.za/'),
    store('Tech', 'Computer Mania', 'https://computermania.co.za/'),
    store('Tech', 'Wireless Camera', 'https://wirelesscamera.co.za/'),
    store('Tech', 'Light Market', 'https://www.lightmarket.co.za/'),
    store('Tech', 'New World', 'https://newworld.co.za/'),
    store('Tech', 'iStore', 'https://www.istore.co.za/'),
    store('Tech', 'iStore Pre-owned', 'https://istorepreowned.co.za/'),
    store('Tech', 'AudioHead', 'https://www.audiohead.co.za/'),
    store('Tech', 'FirstShop', 'https://www.firstshop.co.za/'),
    store('Tech', 'PC International', 'https://pcinternational.co.za/'),
    store('Tech', 'Ink Station', 'https://inkstation.co.za/'),
    store('Tech', 'Incredible Connection', 'https://www.incredible.co.za/'),
    store('Tech', 'HiFi Corp', 'https://www.hificorp.co.za/'),
    store('Tech', 'Syntech', 'https://www.syntech.co.za/'),
    store('Tech', 'Matrix Warehouse', 'https://matrixwarehouse.co.za/'),
    store('Tech', 'Communica', 'https://www.communica.co.za/'),
    store('Tech', 'Switchcom Distribution', 'https://www.switchcom.co.za/'),
    store('Tech', 'Rentoza', 'https://rentoza.co.za/'),
    store('Tech', 'Hisense South Africa', 'https://hisense.co.za/'),
    // Gaming
    store('Gaming', 'HeadsUp SA', 'https://headsupsa.co.za/'),
    store('Gaming', 'BT Games', 'https://btgames.co.za/'),
    store('Gaming', 'Rebel Gaming', 'https://rebelgaming.co.za/'),
    store('Gaming', 'Galactic Traders', 'https://galactictraders.co.za/'),
    store('Gaming', 'GAME 4U', 'https://game4u.co.za/'),
    store('Gaming', 'WeAreGamers', 'https://wearegamers.co.za/'),
    store('Gaming', 'Redragon SA', 'https://redragon.co.za/'),
    // Cameras and drones
    store('Cameras', 'Foto Discount World', 'https://www.fotodiscountworld.co.za/'),
    store('Cameras', 'CameraStuff', 'https://camerastuff.co.za/'),
    store('Cameras', 'Camera Warehouse', 'https://www.camerawarehouse.co.za/'),
    store('Cameras', 'Cine Photo Tools', 'https://cinephototools.co.za/'),
    store('Cameras', 'Outdoorphoto', 'https://www.outdoorphoto.co.za/'),
    store('Cameras', 'Orms Direct', 'https://www.ormsdirect.co.za/'),
    store('Cameras', 'Cameraland', 'https://cameraland.co.za/'),
    store('Cameras', 'GoUAV', 'https://gouav.co.za/'),
    // Daily deals
    store('Deals', 'Hyperli', 'https://hyperli.com/'),
    store('Deals', 'PerfectDealz', 'https://perfectdealz.co.za/'),
    store('Deals', 'FomoSA', 'https://fomosa.co.za/'),
    store('Deals', 'Looters', 'https://looters.co.za/'),
    // Fashion and footwear
    store('Fashion', 'Kheper Activewear', 'https://kheper.co.za/'),
    store('Fashion', 'Koko Active', 'https://kokoactive.co.za/'),
    store('Fashion', 'The Space', 'https://thespace.co.za/'),
    store('Fashion', 'Chepa Streetwear', 'https://www.chepa.co.za/'),
    store('Fashion', 'Shoe Box', 'https://shoebox.co.za/'),
    store('Fashion', 'Bathu', 'https://www.bathu.co.za/'),
    store('Fashion', 'Angelwear', 'https://angelwear.co.za/'),
    store('Fashion', 'Bash', 'https://bash.com/'),
    store('Fashion', 'Johnos Skate Shop', 'https://johnosskateshop.co.za/'),
    store('Fashion', 'Tekkie Town', 'https://tekkietown.co.za/'),
    store('Fashion', 'ChooseMe Intimate', 'https://chooseme.co.za/'),
    store('Fashion', 'Ackermans', 'https://www.ackermans.co.za/'),
    store('Fashion', 'The Sole Provider', 'https://thesoleprovider.co.za/'),
    store('Fashion', 'Livv Activewear', 'https://www.livvactivewear.co.za/'),
    store('Fashion', 'Swest Kicks', 'https://swestkicks.co.za/'),
    store('Fashion', 'The Store Stuff', 'https://www.thestorestuff.co.za/'),
    store('Fashion', 'Butan', 'https://butan.co.za/'),
    store('Fashion', 'Komsurf', 'https://komsurf.com/'),
    store('Fashion', 'K-Swiss South Africa', 'https://www.kswiss.co.za/'),
    store('Fashion', 'Edgars', 'https://www.edgars.co.za/'),
    store('Fashion', 'Boardhub', 'https://www.boardhub.co.za/'),
    store('Fashion', 'Darkstar Direct', 'https://darkstardirect.co.za/'),
    store('Fashion', 'Tigerlilly', 'https://tigerlilly.co.za/'),
    store('Fashion', 'PEP', 'https://www.pepstores.com/'),
    store('Fashion', 'Studio 88', 'https://www.studio-88.co.za/'),
    // Home, furniture and bedding
    store('Home', 'Direct Deals', 'https://directdeals.co.za/'),
    store('Home', 'Decofurn', 'https://decofurnsa.co.za/'),
    store('Home', 'Homzy', 'https://homzy.co.za/'),
    store('Home', 'Coricraft', 'https://coricraft.co.za/'),
    store('Home', 'Linen and Bath', 'https://linenandbath.co.za/'),
    store('Home', 'Online Braai Shop', 'https://onlinebraaishop.co.za/'),
    store('Home', 'Dial-a-Bed', 'https://www.dialabed.co.za/'),
    store('Home', 'Bargains Online', 'https://www.bargainsonline.co.za/'),
    store('Home', 'Drommedaris', 'https://drommedaris.co.za/'),
    store('Home', 'The Mattress Warehouse', 'https://www.themattresswarehouse.co.za/'),
    store('Home', 'The Bedroom Shop Online', 'https://www.thebedroomshoponline.co.za/'),
    store('Home', 'Patio Warehouse', 'https://www.patiowarehouse.co.za/'),
    store('Home', 'The Bed Centre', 'https://thebedcentre.co.za/'),
    store('Home', 'Mojo Beds', 'https://www.mojobeds.co.za/'),
    store('Home', 'The Mattress Company', 'https://the-mattress-company.co.za/'),
    store('Home', 'Linen Lifestyle', 'https://linenlifestyle.co.za/'),
    store('Home', 'Fit For Bed', 'https://www.fit.co.za/'),
    store('Home', 'Beds Online', 'https://www.bedsonline.co.za/'),
    store('Home', 'Chef Gas Braais', 'https://chef.co.za/'),
    store('Home', 'Weylandts', 'https://www.weylandts.co.za/'),
    store('Home', 'Russells', 'https://www.russells.co.za/'),
    store('Home', 'Bradlows', 'https://www.bradlows.co.za/'),
    store('Home', 'Sheet Street', 'https://www.sheetstreet.com/'),
    // Baby and kids
    store('Baby', 'Baby Closet', 'https://babyscloset.co.za/'),
    store('Baby', 'Tiny Necessities', 'https://www.tinynecessities.co.za/'),
    store('Baby', 'Baby City', 'https://www.babycity.co.za/'),
    store('Baby', 'NOOLA', 'https://www.noola.co.za/'),
    store('Baby', 'Kids Living', 'https://kidsliving.co.za/'),
    store('Baby', 'Babies R Us', 'https://www.babiesrus.co.za/'),
    // Pets
    store('Pets', 'Petworld Online', 'https://petworld.co.za/'),
    store('Pets', 'Canine and Co', 'https://canineandco.co.za/'),
    // Sport and outdoor
    store('Sport', 'Bike Addict', 'https://bike-addict.co.za/'),
    store('Sport', 'Camp and Climb', 'https://campandclimb.co.za/'),
    store('Sport', 'Buycycle', 'https://www.buycycle.co.za/'),
    store('Sport', 'The Kingfisher', 'https://www.kingfisher.co.za/'),
    store('Sport', 'Blades and Outdoor', 'https://blades-and-outdoor.co.za/'),
    store('Sport', 'Naturehike Africa', 'https://www.naturehike.co.za/'),
    store('Sport', 'Drifters Adventure Centre', 'https://www.driftersshop.co.za/'),
    store('Sport', 'The Fishing Specialist', 'https://fishingstore.co.za/'),
    store('Sport', 'Tackle Cabin SA', 'https://tacklecabin.co.za/'),
    store('Sport', 'Bike and Tackle', 'https://bikeandtackle.co.za/'),
    store('Sport', 'Safari Outdoor', 'https://safarioutdoor.co.za/'),
    store('Sport', 'Hi-Tec', 'https://hi-tec.co.za/'),
    // Health and supplements
    store('Health', 'Xtreme Nutrition', 'https://xtremenutrition.co.za/'),
    store('Health', 'Feel Healthy', 'https://www.feelhealthy.co.za/'),
    store('Health', 'Health Synergy', 'https://healthsynergy.co.za/'),
    store('Health', 'Fresh Earth Food Store', 'https://freshearth.co.za/'),
    store('Health', 'SSA Supplements', 'https://ssasupplements.com/'),
    store('Health', 'USN South Africa', 'https://za.usn.global/'),
    store('Health', 'Fitness Empire', 'https://fitnessempire.co.za/'),
    // Beauty and hair
    store('Beauty', 'AbsoluteSkin', 'https://absoluteskin.co.za/'),
    store('Beauty', 'Shara Hair', 'https://sharahair.co.za/'),
    store('Beauty', 'Hair City', 'https://www.haircity.co.za/'),
    store('Beauty', 'Hair Majesty', 'https://www.hairmajesty.co.za/'),
    store('Beauty', 'Cosmetology', 'https://www.cosmetology.co.za/'),
    store('Beauty', 'NiceHair SA', 'https://nicehairsa.co.za/'),
    store('Beauty', 'BeautyOnTApp', 'https://beautyontapp.com/'),
    store('Beauty', 'Glamouriche', 'https://glamouriche.co.za/'),
    store('Beauty', 'Cosmetics SA', 'https://cosmeticsa.co.za/'),
    store('Beauty', 'Wellness Warehouse', 'https://wellnesswarehouse.com/'),
    store('Beauty', 'Dermastore', 'https://dermastore.co.za/'),
    store('Beauty', 'Sorbet', 'https://www.sorbet.co.za/'),
    // Food and drink
    store('Groceries', 'Biltong Boytjies', 'https://www.biltongboytjies.co.za/'),
    store('Groceries', 'Cape Coffee Beans', 'https://capecoffeebeans.co.za/'),
    store('Groceries', 'Bean There Coffee', 'https://beanthere.co.za/'),
    store('Groceries', 'Slivers Biltong and Nuts', 'https://slivers.co.za/'),
    store('Groceries', 'Bean Online', 'https://beanonline.co.za/'),
    store('Liquor', 'Getwine', 'https://www.getwine.co.za/'),
    store('Liquor', 'Winetime Online', 'https://winetimeonline.co.za/'),
    store('Liquor', 'Winefolk', 'https://winefolk.co.za/'),
    store('Liquor', 'Vinty Wines', 'https://vinty.co.za/'),
    store('Liquor', 'Norman Goodfellows', 'https://www.ngf.co.za/'),
    store('Liquor', 'Bar Keeper', 'https://barkeeper.co.za/'),
    store('Liquor', 'Mothercity Liquor', 'https://mothercityliquor.co.za/'),
    // Books, toys, art and office
    store('Books', 'Readers Warehouse', 'https://www.readerswarehouse.co.za/'),
    store('Books', 'Caxton Books', 'https://caxtonbooks.co.za/'),
    store('Books', 'Van Schaik Bookstore', 'https://www.vanschaik.com/'),
    store('Books', 'Wordsworth Books', 'https://www.wordsworth.co.za/'),
    store('Books', 'Exclusive Books', 'https://exclusivebooks.co.za/'),
    store('Toys', 'Toy Kingdom', 'https://toykingdom.co.za/'),
    store('Toys', 'The Hidden Den', 'https://thehiddenden.co.za/'),
    store('Toys', 'Toys R Us South Africa', 'https://www.toysrus.co.za/'),
    store('Art', 'Art Savings Club', 'https://artsavingsclub.co.za/'),
    store('Art', 'Art Images', 'https://www.artimages.co.za/'),
    store('Art', 'Deckle Edge', 'https://www.deckleedge.co.za/'),
    store('Art', 'Craftup', 'https://craftup.co.za/'),
    store('Office', 'MHC World', 'https://www.mhcworld.co.za/'),
    store('Office', 'Penfile', 'https://www.penfile.co.za/'),
    store('Office', 'PNA', 'https://www.pna.co.za/'),
    // Music
    store('Music', 'Music Experience', 'https://www.musicexperience.co.za/'),
    store('Music', 'Sound Select ZA', 'https://soundselect.co.za/'),
    store('Music', 'Bothners', 'https://bothners.co.za/'),
    store('Music', 'Marshall Music', 'https://www.marshallmusic.co.za/'),
    store('Music', 'OneStop Music', 'https://onestopmusic.co.za/'),
    store('Music', 'Guitar Gallery', 'https://guitargallery.co.za/'),
    // Garden
    store('Garden', 'Stodels', 'https://www.stodels.com/'),
    store('Garden', 'ClicknPlant', 'https://www.clicknplant.co.za/'),
    store('Garden', 'Plantland', 'https://plantland.co.za/'),
    store('Garden', 'Gardening South Africa', 'https://gardening.co.za/'),
    store('Garden', 'Cape Garden Centre', 'https://www.capegardencentre.co.za/'),
    // Workwear, jewellery and eyewear
    store('Workwear', 'Pinnacle Shop', 'https://pinnacleshop.co.za/'),
    store('Jewellery', 'Police Lifestyle', 'https://www.policelifestyle.co.za/'),
    store('Eyewear', 'Oculux', 'https://www.oculux.co.za/'),
    // Motoring
    store('Motoring', 'Spares Direct', 'https://sparesdirect.co.za/'),
    store('Motoring', 'AutoSupply', 'https://autosupply.co.za/'),
    store('Motoring', 'Midas', 'https://midas.co.za/'),
    store('Motoring', 'Start My Car', 'https://www.startmycar.co.za/'),
    store('Motoring', 'Tiger Wheel and Tyre', 'https://twt.co.za/'),
    // Hardware and general
    store('Hardware', 'Gelmar', 'https://www.gelmar.co.za/'),
    store('Hardware', 'Leroy Merlin South Africa', 'https://leroymerlin.co.za/'),
    store('Hardware', 'Brights Hardware', 'https://www.brights.co.za/'),
    store('Hardware', 'Chamberlains', 'https://www.chamberlains.co.za/'),
    store('General', 'SuperbHyper', 'https://superbhyper.co.za/'),
    store('General', 'FairPrice Online', 'https://www.fairprice.co.za/'),
    store('General', 'OK Furniture', 'https://www.okfurniture.co.za/'),
  ],
  // Netherlands. Of 595 hosts probed in July 2026 these answered with a working
  // product feed, and the shape of the result is the opposite of a big-chains
  // strategy: not one top-20 Dutch retailer is reachable except Lidl. bol.com,
  // Coolblue, Albert Heijn, Jumbo, Zalando and Picnic all sit behind
  // Cloudflare, Akamai or Imperva — Akamai blocks even the well-known
  // anonymous Albert Heijn and Jumbo mobile APIs — so each would need its own
  // adapter and, for several, an issued partner key.
  //
  // What does work is the long tail: Shopify, Magento GraphQL, WooCommerce and
  // Lightspeed shops. Every Lightspeed shop probed converted, which makes that
  // platform the cheapest way to grow Dutch coverage from here.
  //
  // Amounts are euros except two shops whose Shopify primary market is not the
  // Netherlands, and the same presentment-currency caution as the United
  // States applies: a discount reads the same in any currency, but the amount
  // is only euros when the request comes from Europe.
  NL: [
    // Baby
    store("Baby", "Babywinkel.nl", "https://www.babywinkel.nl/"),
    store("Baby", "Prenatal", "https://www.prenatal.nl/"),
    // Books & toys
    store("Books & toys", "De Speelgoedwinkel", "https://www.despeelgoedwinkel.nl/"),
    store("Books & toys", "Houtenspeelgoed.nl", "https://houtenspeelgoed.nl/"),
    // DIY
    store("DIY", "Pronto Wonen", "https://www.prontowonen.nl/"),
    store("DIY", "Hubo", "https://www.hubo.nl/"),
    store("DIY", "Bouwmaat", "https://www.bouwmaat.nl/"),
    // Fashion
    store("Fashion", "Mos Mosh", "https://mosmosh.com/"),
    store("Fashion", "Daily Paper", "https://dailypaperclothing.com/"),
    store("Fashion", "Snurk", "https://snurkamsterdam.com/"),
    store("Fashion", "Sapph", "https://www.sapph.com/"),
    store("Fashion", "Quotrell", "https://www.quotrell.com/"),
    store("Fashion", "Fabienne Chapot", "https://www.fabiennechapot.com/"),
    store("Fashion", "Black Bananas", "https://www.blackbananas.nl/"),
    store("Fashion", "Aaiko", "https://aaiko.com/"),
    store("Fashion", "Pockies", "https://www.pockies.com/"),
    store("Fashion", "Marlies Dekkers", "https://www.marliesdekkers.com/"),
    store("Fashion", "Purdey", "https://www.purdey.nl/"),
    store("Fashion", "Ballin Amsterdam", "https://www.ballinamsterdam.com/"),
    store("Fashion", "Oger", "https://oger.nl/"),
    store("Fashion", "MUD Jeans", "https://mudjeans.com/"),
    store("Fashion", "Dstrezzed", "https://www.dstrezzed.com/"),
    store("Fashion", "Brandfield", "https://www.brandfield.nl/"),
    store("Fashion", "Wolky", "https://www.wolky.nl/"),
    store("Fashion", "Filling Pieces", "https://www.fillingpieces.com/"),
    store("Fashion", "Malelions", "https://www.malelions.com/"),
    store("Fashion", "Catwalk Junkie", "https://www.catwalkjunkie.com/"),
    store("Fashion", "Olaf Hussein", "https://www.olafhussein.com/"),
    store("Fashion", "Hip voor de Heb", "https://hipvoordeheb.nl/"),
    store("Fashion", "LongLady", "https://www.longlady.nl/"),
    store("Fashion", "Otrium", "https://www.otrium.nl/"),
    store("Fashion", "Tenue de Nimes", "https://tenuedenimes.com/"),
    store("Fashion", "Kuyichi", "https://kuyichi.com/"),
    store("Fashion", "Terstal", "https://www.terstal.nl/"),
    store("Fashion", "Patta", "https://patta.nl/"),
    store("Fashion", "PME Legend", "https://www.pme-legend.com/"),
    store("Fashion", "Vanguard", "https://vanguard.pme-legend.com/"),
    store("Fashion", "Scotch & Soda", "https://scotchandsoda.com/"),
    store("Fashion", "Durlinger", "https://www.durlinger.com/"),
    store("Fashion", "Jollein", "https://jollein.com/"),
    store("Fashion", "Travelbags", "https://www.travelbags.nl/"),
    store("Fashion", "Vingino", "https://www.vingino.com/"),
    store("Fashion", "Zinzi", "https://www.zinzi.nl/"),
    // Food & drink
    store("Food & drink", "Whiskysite", "https://www.whiskysite.nl/"),
    store("Food & drink", "Koffiestore", "https://koffiestore.nl/"),
    store("Food & drink", "Theeshop.nl", "https://www.theeshop.nl/"),
    store("Food & drink", "Pit&Pit", "https://nl.pit-pit.com/"),
    store("Food & drink", "De Notenshop", "https://www.denotenshop.nl/"),
    store("Food & drink", "Espressoshop", "https://espressoshop.nl/"),
    store("Food & drink", "Noten.nl", "https://noten.nl/"),
    store("Food & drink", "Koffiecentrale", "https://www.koffiecentrale.nl/"),
    store("Food & drink", "Grandcru Wijnen", "https://www.grandcruwijnen.nl/"),
    store("Food & drink", "Beerwulf", "https://eu.beerwulf.com/"),
    store("Food & drink", "Kaasgilde", "https://www.kaasgilde.nl/"),
    store("Food & drink", "Notenbar", "https://notenbar.nl/"),
    store("Food & drink", "Tony's Chocolonely", "https://tonyschocolonely.com/"),
    // General
    store("General", "Feestbazaar", "https://www.feestbazaar.nl/"),
    store("General", "Dekbed-Discounter", "https://www.dekbed-discounter.nl/"),
    store("General", "Voordeelvanger", "https://www.voordeelvanger.nl/"),
    store("General", "Dealdonkey", "https://www.dealdonkey.com/"),
    store("General", "Dille & Kamille", "https://www.dille-kamille.nl/"),
    store("General", "Giftcampaign NL", "https://www.giftcampaign.nl/"),
    // Grocery
    store("Grocery", "Lidl NL", "https://www.lidl.nl/"),
    // Health & beauty
    store("Health & beauty", "Kappersgroothandel", "https://kappersgroothandel.nl/"),
    store("Health & beauty", "Parfumswinkel", "https://www.parfumswinkel.nl/"),
    store("Health & beauty", "Huidproducten.nl", "https://huidproducten.nl/"),
    store("Health & beauty", "Body & Fit", "https://www.bodyandfit.com/"),
    store("Health & beauty", "Haarspullen.nl", "https://www.haarspullen.nl/"),
    store("Health & beauty", "Beautyplaza", "https://www.beautyplaza.com/"),
    store("Health & beauty", "Lucovitaal", "https://www.lucovitaal.nl/"),
    // Hobby
    store("Hobby", "Partywinkel", "https://www.partywinkel.nl/"),
    store("Hobby", "Feestwinkel", "https://www.feestwinkel.nl/"),
    store("Hobby", "Wolplein", "https://www.wolplein.nl/"),
    store("Hobby", "Pipoos", "https://pipoos.com/"),
    store("Hobby", "Velvet Music", "https://www.velvetmusic.nl/"),
    // Home
    store("Home", "Directlampen", "https://www.directlampen.nl/"),
    store("Home", "Vloerenwinkel", "https://vloerenwinkel.nl/"),
    store("Home", "Cookinglife", "https://www.cookinglife.nl/"),
    store("Home", "Fonteyn", "https://fonteyn.nl/"),
    store("Home", "Bakker (Bakker Hillegom)", "https://nl-nl.bakker.com/"),
    store("Home", "Tuinmeubelshop", "https://www.tuinmeubelshop.nl/"),
    store("Home", "Bohemian Living", "https://www.bohemian-living.nl/"),
    store("Home", "Flying Tiger NL", "https://flyingtiger.com/"),
    store("Home", "Lampencompleet", "https://lampencompleet.nl/"),
    store("Home", "De Kokswinkel", "https://kokswinkel.nl/"),
    store("Home", "Sanitairkamer", "https://sanitairkamer.nl/"),
    store("Home", "Beddinghouse", "https://www.beddinghouse.com/"),
    store("Home", "Eijerkamp", "https://www.eijerkamp.nl/"),
    store("Home", "Riviera Maison", "https://rivieramaison.com/"),
    // Pets
    store("Pets", "Horze NL", "https://horze.nl/"),
    store("Pets", "DRD Knaagdierwinkel", "https://www.drdknaagdierwinkel.nl/"),
    store("Pets", "Petsonline", "https://www.petsonline.nl/"),
    store("Pets", "DierenwinkelXL", "https://dierenwinkelxl.nl/"),
    // Sport
    store("Sport", "Soccerfanshop", "https://www.soccerfanshop.nl/"),
    store("Sport", "Fietsdirect", "https://www.fietsdirect.nl/"),
    store("Sport", "Bikester NL", "https://www.bikester.nl/"),
    store("Sport", "Fitwinkel", "https://fitwinkel.nl/"),
    store("Sport", "Divoza Horseworld", "https://divoza.com/"),
    store("Sport", "Rogelli", "https://rogelli.com/"),
    store("Sport", "Yogashop", "https://www.yogashop.nl/"),
    store("Sport", "Telstar Surf", "https://www.telstarsurf.com/"),
    store("Sport", "Intersport NL", "https://intersport.nl/"),
    store("Sport", "Batavus", "https://batavus.com/"),
    store("Sport", "Gazelle", "https://www.gazelle.nl/"),
    // Tech
    store("Tech", "Sound Gallery", "https://www.soundgallery.nl/"),
    store("Tech", "Hobbyelectronica", "https://www.hobbyelectronica.nl/"),
    store("Tech", "Leapp", "https://leapp.nl/"),
    store("Tech", "Ledwinkel", "https://ledwinkel-online.nl/"),
    store("Tech", "Otronic", "https://www.otronic.nl/"),
    store("Tech", "Antratek", "https://www.antratek.nl/"),
    store("Tech", "Elektramat", "https://www.elektramat.nl/"),
    // Tools & auto
    store("Tools & auto", "Toolnation", "https://www.toolnation.nl/"),
  ],
  // United States. Of 544 sites probed in July 2026 these answered with a
  // working discount feed, and almost every one is Shopify. The large national
  // chains — Walmart, Target, Kroger, Costco, CVS, Home Depot — are all behind
  // bot management or render client-side, so none is reachable this way; each
  // would need its own adapter, most realistically through the developer or
  // affiliate APIs several of them publish.
  //
  // One caution for the amounts. A Shopify Markets shop answers products.json
  // in the presentment currency of whoever asks, so a sweep egressing outside
  // the United States can be handed converted figures. Finding the discount is
  // unaffected, because a compare-at price above the selling price means the
  // same in any currency, but the amounts are only dollars when the request
  // comes from the United States.
  US: [
    // Baby
    store("Baby", "Bobbie", "https://www.hibobbie.com/"),
    store("Baby", "Bumbleride", "https://bumbleride.com/"),
    store("Baby", "Honest Company", "https://www.honest.com/"),
    store("Baby", "Lalo", "https://www.meetlalo.com/"),
    store("Baby", "Nanit", "https://www.nanit.com/"),
    store("Baby", "Owlet", "https://owletcare.com/"),
    store("Baby", "Solly Baby", "https://sollybaby.com/"),
    // Beauty
    store("Beauty", "Beautycounter", "https://www.beautycounter.com/"),
    store("Beauty", "Beekman 1802", "https://beekman1802.com/"),
    store("Beauty", "Bliss", "https://blissworld.com/"),
    store("Beauty", "ColourPop", "https://colourpop.com/"),
    store("Beauty", "Dr. Squatch", "https://drsquatch.com/"),
    store("Beauty", "Duke Cannon", "https://www.dukecannon.com/"),
    store("Beauty", "First Aid Beauty", "https://www.firstaidbeauty.com/"),
    store("Beauty", "Function of Beauty", "https://www.functionofbeauty.com/"),
    store("Beauty", "Glossier", "https://www.glossier.com/"),
    store("Beauty", "Ilia Beauty", "https://iliabeauty.com/"),
    store("Beauty", "Jeffree Star Cosmetics", "https://jeffreestarcosmetics.com/"),
    store("Beauty", "Kylie Cosmetics", "https://kyliecosmetics.com/"),
    store("Beauty", "Milk Makeup", "https://www.milkmakeup.com/"),
    store("Beauty", "Morphe", "https://www.morphe.com/"),
    store("Beauty", "Native", "https://www.nativecos.com/"),
    store("Beauty", "Olaplex", "https://olaplex.com/"),
    store("Beauty", "Thrive Causemetics", "https://thrivecausemetics.com/"),
    store("Beauty", "Tula Skincare", "https://www.tula.com/"),
    store("Beauty", "Vegamour", "https://vegamour.com/"),
    store("Beauty", "Versed Skin", "https://versedskin.com/"),
    // Eyewear
    store("Eyewear", "Blenders Eyewear", "https://www.blenderseyewear.com/"),
    store("Eyewear", "Goodr", "https://goodr.com/"),
    store("Eyewear", "Knockaround", "https://knockaround.com/"),
    store("Eyewear", "Sunski", "https://sunski.com/"),
    // Fashion
    store("Fashion", "Alex Mill", "https://www.alexmill.com/"),
    store("Fashion", "Allbirds", "https://www.allbirds.com/"),
    store("Fashion", "Altra Running", "https://www.altrarunning.com/"),
    store("Fashion", "American Giant", "https://www.american-giant.com/"),
    store("Fashion", "Astral Designs", "https://astraldesigns.com/"),
    store("Fashion", "Aviator Nation", "https://aviatornation.com/"),
    store("Fashion", "Boody US", "https://boodywear.com/"),
    store("Fashion", "Born Primitive", "https://bornprimitive.com/"),
    store("Fashion", "Carve Designs", "https://carvedesigns.com/"),
    store("Fashion", "Cotopaxi", "https://www.cotopaxi.com/"),
    store("Fashion", "Everlane", "https://www.everlane.com/"),
    store("Fashion", "Faherty", "https://fahertybrand.com/"),
    store("Fashion", "Free Fly Apparel", "https://www.freeflyapparel.com/"),
    store("Fashion", "Girlfriend Collective", "https://girlfriend.com/"),
    store("Fashion", "Howler Brothers", "https://howlerbros.com/"),
    store("Fashion", "Johnnie-O", "https://johnnie-o.com/"),
    store("Fashion", "Johnny Cupcakes", "https://johnnycupcakes.com/"),
    store("Fashion", "Keen Footwear", "https://www.keenfootwear.com/"),
    store("Fashion", "Kizik", "https://kizik.com/"),
    store("Fashion", "Life is Good", "https://www.lifeisgood.com/"),
    store("Fashion", "Mack Weldon", "https://mackweldon.com/"),
    store("Fashion", "Marine Layer", "https://www.marinelayer.com/"),
    store("Fashion", "Nisolo", "https://nisolo.com/"),
    store("Fashion", "NOBULL", "https://www.nobullproject.com/"),
    store("Fashion", "Oliver Cabell", "https://olivercabell.com/"),
    store("Fashion", "Outdoor Voices", "https://www.outdoorvoices.com/"),
    store("Fashion", "Psycho Bunny", "https://www.psychobunny.com/"),
    store("Fashion", "Roark", "https://www.roark.com/"),
    store("Fashion", "Rothy's", "https://rothys.com/"),
    store("Fashion", "Rue21", "https://rue21.com/"),
    store("Fashion", "Southern Tide", "https://southerntide.com/"),
    store("Fashion", "Sperry", "https://www.sperry.com/"),
    store("Fashion", "Taylor Stitch", "https://www.taylorstitch.com/"),
    store("Fashion", "Tentree", "https://www.tentree.com/"),
    store("Fashion", "Thursday Boots", "https://thursdayboots.com/"),
    store("Fashion", "Toad&Co", "https://www.toadandco.com/"),
    store("Fashion", "Untuckit", "https://www.untuckit.com/"),
    store("Fashion", "Vessi", "https://vessi.com/"),
    store("Fashion", "Vollebak", "https://vollebak.com/"),
    store("Fashion", "Xero Shoes", "https://xeroshoes.com/"),
    // General
    store("General", "Big Lots", "https://www.biglots.com/"),
    store("General", "Party City", "https://www.partycity.com/"),
    // Groceries
    store("Groceries", "Atlas Coffee Club", "https://atlascoffeeclub.com/"),
    store("Groceries", "Bare Bones", "https://barebonesbroth.com/"),
    store("Groceries", "Blk & Bold", "https://blkandbold.com/"),
    store("Groceries", "Bones Coffee", "https://bonescoffee.com/"),
    store("Groceries", "Brightland", "https://brightland.co/"),
    store("Groceries", "Bulletproof", "https://www.bulletproof.com/"),
    store("Groceries", "Chomps", "https://chomps.com/"),
    store("Groceries", "Coffee Bean Direct", "https://www.coffeebeandirect.com/"),
    store("Groceries", "Coffee Bros", "https://coffeebros.com/"),
    store("Groceries", "Cometeer", "https://cometeer.com/"),
    store("Groceries", "Copper Cow Coffee", "https://coppercowcoffee.com/"),
    store("Groceries", "Counter Culture Coffee", "https://counterculturecoffee.com/"),
    store("Groceries", "Country Archer", "https://countryarcher.com/"),
    store("Groceries", "Death Wish Coffee", "https://www.deathwishcoffee.com/"),
    store("Groceries", "EPIC Provisions", "https://epicprovisions.com/"),
    store("Groceries", "Fly By Jing", "https://flybyjing.com/"),
    store("Groceries", "Four Sigmatic", "https://us.foursigmatic.com/"),
    store("Groceries", "Graza", "https://www.graza.co/"),
    store("Groceries", "Intelligentsia Coffee", "https://www.intelligentsia.com/"),
    store("Groceries", "Kettle & Fire", "https://www.kettleandfire.com/"),
    store("Groceries", "Klatch Coffee", "https://klatchroasting.com/"),
    store("Groceries", "Kodiak Cakes", "https://kodiakcakes.com/"),
    store("Groceries", "La Colombe", "https://www.lacolombe.com/"),
    store("Groceries", "Laird Superfood", "https://lairdsuperfood.com/"),
    store("Groceries", "Lesser Evil", "https://lesserevil.com/"),
    store("Groceries", "Lifeboost Coffee", "https://lifeboostcoffee.com/"),
    store("Groceries", "Magic Spoon", "https://magicspoon.com/"),
    store("Groceries", "Momofuku Goods", "https://shop.momofuku.com/"),
    store("Groceries", "Nuts.com", "https://nuts.com/"),
    store("Groceries", "Oh Nuts", "https://www.ohnuts.com/"),
    store("Groceries", "Onyx Coffee Lab", "https://onyxcoffeelab.com/"),
    store("Groceries", "Perfect Snacks", "https://perfectsnacks.com/"),
    store("Groceries", "Pipcorn", "https://www.pipsnacks.com/"),
    store("Groceries", "Purely Elizabeth", "https://purelyelizabeth.com/"),
    store("Groceries", "Stumptown Coffee", "https://www.stumptowncoffee.com/"),
    store("Groceries", "Truff", "https://truff.com/"),
    store("Groceries", "Verve Coffee", "https://www.vervecoffee.com/"),
    store("Groceries", "Vital Proteins", "https://www.vitalproteins.com/"),
    store("Groceries", "Volcanica Coffee", "https://volcanicacoffee.com/"),
    store("Groceries", "Wandering Bear Coffee", "https://wanderingbearcoffee.com/"),
    store("Groceries", "Wild Zora", "https://wildzora.com/"),
    // Hardware
    store("Hardware", "Ohio Power Tool", "https://www.ohiopowertool.com/"),
    store("Hardware", "Tool Nut", "https://www.toolnut.com/"),
    // Health
    store("Health", "1st Phorm", "https://1stphorm.com/"),
    store("Health", "Alani Nu", "https://www.alaninu.com/"),
    store("Health", "Bare Performance Nutrition", "https://bpnsupps.com/"),
    store("Health", "BulkSupplements", "https://www.bulksupplements.com/"),
    store("Health", "Do Vitamins", "https://dovitamins.com/"),
    store("Health", "Ghost Lifestyle", "https://www.ghostlifestyle.com/"),
    store("Health", "Gnarly Nutrition", "https://www.gognarly.com/"),
    store("Health", "Jocko Fuel", "https://jockofuel.com/"),
    store("Health", "Kaged", "https://www.kaged.com/"),
    store("Health", "Momentous", "https://www.livemomentous.com/"),
    store("Health", "Naked Nutrition", "https://nakednutrition.com/"),
    store("Health", "Nutrabio", "https://www.nutrabio.com/"),
    store("Health", "Nutricost", "https://nutricost.com/"),
    store("Health", "Onnit", "https://www.onnit.com/"),
    store("Health", "Raw Nutrition", "https://getrawnutrition.com/"),
    store("Health", "Redcon1", "https://redcon1.com/"),
    store("Health", "Ryse Supps", "https://rysesupps.com/"),
    store("Health", "Swanson Vitamins", "https://www.swansonvitamins.com/"),
    store("Health", "Transparent Labs", "https://www.transparentlabs.com/"),
    // Hobby
    store("Hobby", "Elemental Games alt: Grognard Games", "https://grognardgames.com/"),
    store("Hobby", "Fabric Wholesale Direct", "https://www.fabricwholesaledirect.com/"),
    store("Hobby", "Gamers Guild AZ", "https://www.gamersguildaz.com/"),
    store("Hobby", "Golden Wolf alt: Dice Envy", "https://diceenvy.com/"),
    store("Hobby", "Micro-Mark", "https://www.micromark.com/"),
    store("Hobby", "Missouri Star Quilt Co", "https://www.missouriquiltco.com/"),
    store("Hobby", "Mood Fabrics", "https://www.moodfabrics.com/"),
    store("Hobby", "Tabletop Tycoon", "https://tabletoptycoon.com/"),
    store("Hobby", "Woodcraft", "https://www.woodcraft.com/"),
    store("Hobby", "Wyrmwood Gaming", "https://wyrmwoodgaming.com/"),
    // Home
    store("Home", "Avocado Green Mattress", "https://www.avocadogreenmattress.com/"),
    store("Home", "Bearaby", "https://bearaby.com/"),
    store("Home", "Buffy", "https://buffy.co/"),
    store("Home", "Corkcicle", "https://corkcicle.com/"),
    store("Home", "Coyuchi", "https://www.coyuchi.com/"),
    store("Home", "Floyd Home", "https://floydhome.com/"),
    store("Home", "Great Jones", "https://greatjonesgoods.com/"),
    store("Home", "HexClad", "https://hexclad.com/"),
    store("Home", "Lodge Cast Iron", "https://www.lodgecastiron.com/"),
    store("Home", "Lulu and Georgia", "https://www.luluandgeorgia.com/"),
    store("Home", "Material Kitchen", "https://materialkitchen.com/"),
    store("Home", "Misen", "https://misen.com/"),
    store("Home", "Our Place", "https://fromourplace.com/"),
    store("Home", "Parachute Home", "https://www.parachutehome.com/"),
    store("Home", "Schoolhouse", "https://schoolhouse.com/"),
    store("Home", "Simple Modern", "https://simplemodern.com/"),
    store("Home", "Snowe", "https://www.snowehome.com/"),
    store("Home", "Stanley 1913", "https://www.stanley1913.com/"),
    store("Home", "Tuft & Needle", "https://www.tuftandneedle.com/"),
    store("Home", "W&P Design", "https://wandpdesign.com/"),
    // Jewellery
    store("Jewellery", "Aurate New York", "https://auratenewyork.com/"),
    store("Jewellery", "Gorjana", "https://gorjana.com/"),
    store("Jewellery", "Nixon", "https://www.nixon.com/"),
    store("Jewellery", "Shinola", "https://www.shinola.com/"),
    store("Jewellery", "Vincero", "https://vincerocollective.com/"),
    // Luggage
    store("Luggage", "Away", "https://www.awaytravel.com/"),
    store("Luggage", "Travelpro", "https://travelpro.com/"),
    // Motoring
    store("Motoring", "Adam's Polishes", "https://adamspolishes.com/"),
    store("Motoring", "Chemical Guys", "https://www.chemicalguys.com/"),
    store("Motoring", "Detroit Axle", "https://detroitaxle.com/"),
    // Music
    store("Music", "Chicago Music Exchange", "https://www.chicagomusicexchange.com/"),
    // Office
    store("Office", "Baron Fig", "https://baronfig.com/"),
    store("Office", "Goulet Pens", "https://www.gouletpens.com/"),
    // Pets
    store("Pets", "Bark", "https://bark.co/"),
    store("Pets", "Bocce's Bakery", "https://boccesbakery.com/"),
    store("Pets", "Cloud Star", "https://cloudstar.com/"),
    store("Pets", "Fable Pets", "https://fablepets.com/"),
    store("Pets", "Native Pet", "https://www.nativepet.com/"),
    store("Pets", "Only Natural Pet", "https://www.onlynaturalpet.com/"),
    store("Pets", "Open Farm", "https://openfarmpet.com/"),
    store("Pets", "PetHonesty", "https://pethonesty.com/"),
    store("Pets", "Wild Earth", "https://wildearth.com/"),
    store("Pets", "Wild One", "https://wildone.com/"),
    // Sport
    store("Sport", "2nd Swing Golf", "https://www.2ndswing.com/"),
    store("Sport", "Big Agnes", "https://www.bigagnes.com/"),
    store("Sport", "BioLite", "https://www.bioliteenergy.com/"),
    store("Sport", "Fringe Sport", "https://www.fringesport.com/"),
    store("Sport", "Garage Grown Gear", "https://www.garagegrowngear.com/"),
    store("Sport", "GoRuck", "https://www.goruck.com/"),
    store("Sport", "Gossamer Gear", "https://www.gossamergear.com/"),
    store("Sport", "Hyperice", "https://hyperice.com/"),
    store("Sport", "Hyperlite Mountain Gear", "https://www.hyperlitemountaingear.com/"),
    store("Sport", "Iron Bull Strength", "https://ironbullstrength.com/"),
    store("Sport", "Kelty", "https://www.kelty.com/"),
    store("Sport", "Nemo Equipment", "https://www.nemoequipment.com/"),
    store("Sport", "Onyx Fitness alt: Bells of Steel", "https://www.bellsofsteel.us/"),
    store("Sport", "Outdoor Research", "https://www.outdoorresearch.com/"),
    store("Sport", "PowerBlock", "https://powerblock.com/"),
    store("Sport", "Priority Bicycles", "https://www.prioritybicycles.com/"),
    store("Sport", "REP Fitness", "https://repfitness.com/"),
    store("Sport", "Rumpl", "https://www.rumpl.com/"),
    store("Sport", "Sea to Summit US", "https://seatosummit.com/"),
    store("Sport", "Six Moon Designs", "https://www.sixmoondesigns.com/"),
    store("Sport", "State Bicycle Co", "https://www.statebicycle.com/"),
    store("Sport", "Theragun/Therabody", "https://www.therabody.com/"),
    store("Sport", "Titan Fitness", "https://www.titan.fitness/"),
    store("Sport", "Topo Designs", "https://topodesigns.com/"),
    store("Sport", "Torque Fitness", "https://torquefitness.com/"),
    // Tech
    store("Tech", "EcoFlow US", "https://us.ecoflow.com/"),
    store("Tech", "Glorious Gaming", "https://www.gloriousgaming.com/"),
    store("Tech", "Goal Zero", "https://www.goalzero.com/"),
    store("Tech", "iFi Audio US", "https://ifi-audio.com/"),
    store("Tech", "Jackery", "https://www.jackery.com/"),
    store("Tech", "Keychron", "https://www.keychron.com/"),
    store("Tech", "Master & Dynamic", "https://www.masterdynamic.com/"),
    store("Tech", "NZXT", "https://nzxt.com/"),
    store("Tech", "Skullcandy", "https://www.skullcandy.com/"),
    store("Tech", "UGREEN US", "https://www.ugreen.com/"),
    store("Tech", "Wyze", "https://www.wyze.com/"),
    // Toys
    store("Toys", "Melissa & Doug", "https://www.melissaanddoug.com/"),
  ],
  ZW: [
    // OK Zimbabwe serves a live WooCommerce catalogue with real grocery
    // markdowns, but its TLS certificate expired in December 2025, so an edge
    // fetch cannot complete the handshake. It is kept here deliberately: the
    // moment the certificate is renewed the scout picks the deals up with no
    // code change, and until then the failure is a clean transient one.
    store('Groceries', 'OK Zimbabwe', 'https://okonline.co.zw/'),
    store('Groceries', 'From Me', 'https://www.fromme.co.zw/'),
    store('Tech', 'Celltrade', 'https://celltrade.co.zw/'),
    store('Tech', 'Laptop Zone', 'https://laptopzone.co.zw/'),
    store('Tech', 'Reeltec Electronics', 'https://reeltecelectronics.co.zw/'),
    store('Tech', 'Spellbound Mobile', 'https://spellboundmobile.com/'),
    store('General', 'Bandauko', 'https://bandauko.co.zw/'),
    store('Home', 'Bhiks Home Stores', 'https://bhikshomestore.co.zw/'),
    store('Hardware', 'Depot Solar', 'https://depotsolar.co.zw/'),
    store('Pharmacy', 'Ayasam', 'https://www.ayasam.co.zw/'),
    store('Fashion', 'The Shoe Barn', 'https://www.theshoebarn.co.zw/'),
    store('Baby', 'Baby Sprouts Zimbabwe', 'https://babysproutszimbabwe.com/'),
  ],
}

export function getOnlineStoreCountryCodes(): string[] {
  return Object.keys(ONLINE_STORE_SOURCES)
}

export function getOnlineStoreSources(countryCode: string): readonly OnlineStoreSource[] {
  return ONLINE_STORE_SOURCES[countryCode.toUpperCase()] ?? []
}
